---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gomzevfh/public_html/ict.gomze.co.za/ 
    - /bin/cp -R assets $DEPLOYPATH   
    - /bin/cp -R css $DEPLOYPATH      
    - /bin/cp -R fonts $DEPLOYPATH    
    - /bin/cp -R img $DEPLOYPATH      
    - /bin/cp -R js $DEPLOYPATH       
    - /bin/cp 404.html $DEPLOYPATH    
    - /bin/cp about-us.html $DEPLOYPATH
    - /bin/cp blog-single.html $DEPLOYPATH
    - /bin/cp blog-standard.html $DEPLOYPATH
    - /bin/cp 'case-single 2.html' $DEPLOYPATH 
    - /bin/cp case-single.html $DEPLOYPATH
    - /bin/cp case-studies.html $DEPLOYPATH
    - /bin/cp consultation.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp faq.html $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp services-single.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp team-single.html $DEPLOYPATH
    - /bin/cp team.html $DEPLOYPATH
    - /bin/cp why-choose-us.html $DEPLOYPATH

